#include <stdio.h>

int main() {
    printf("GAWIOGAWIJOAGWJIOAGWJIOAIJOGWGAIWJOGIJAOWJOIAGWJIOAGWIJOAGWJIOAGWIJOAGWIJOAGWIUHAWFYWRAOGAWAWR&*AWAFSISFIUAFIUHFAHIUAFIHUFASIHUSAKJSAJKASJKJKASJKAJKASJKSAJKASKJSAJKJKSAJKAS\n");
    return 0;
    printf("SALAH CODING OMAGA");
}