#include <stdio.h>

int main() {
    printf("GAWIOGAWIJOAGWJIOAGWJIOAIJOGWGAIWJOGIJAOWJOIAGWJIOAGWIJOAGWJIOAGWIJOAGWIJOAGWIUHAWFYWRAOGAWAWR&*AWAFSISFIUAFIUHFAHIUAFIHUFASIHUSAKJSAJKASJKJKASJKAJKASJKSAJKASKJSAJKJKSAJKAS\n");
    printf("this is a test file for C17 standard.\n");
    return 0;
}