#include <stdio.h>

int main() {
    printf("GAWIOGAWIJOAGWJIOAGWJIOAIJOGWGAIWJOGIJAOWJOIAGWJIOAGWIJOAGWJIOAGWIJOAGWIJOAGWIUHAWFYWRAOGAWAWR&*AWAFSISFIUAFIUHFAHIUAFIHUFASIHUSAKJSAJKASJKJKASJKAJKASJKSAJKASKJSAJKJKSAJKAS\n");
    printf("SALAH CODING OMAGA 2");
    return 0;
}